name: Spring Boot CI/CD with Runner

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  POSTGRES_DB: travel
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Build with Gradle (skip tests)
      run: ./gradlew build -x test
      
    - name: Upload JAR
      uses: actions/upload-artifact@v3
      with:
        name: app-jar
        path: build/libs/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
    - name: Download JAR
      uses: actions/download-artifact@v3
      with:
        name: app-jar
        
    - name: Deploy to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: ${{ secrets.DIGITALOCEAN_USERNAME }}
        key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
        source: "*.jar"
        target: "/opt/travel/"
        
    - name: Start Application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: ${{ secrets.DIGITALOCEAN_USERNAME }}
        key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
        script: |
          # Kill existing process if running
          pid=$(pgrep -f travel)
          if [ ! -z "$pid" ]; then
            kill -9 $pid
          fi
          
          # Start the application
          cd /opt/travel
          nohup java -jar \
            -Dspring.datasource.url=jdbc:postgresql://localhost:5432/${{ env.POSTGRES_DB }} \
            -Dspring.datasource.username=${{ env.POSTGRES_USER }} \
            -Dspring.datasource.password=${{ secrets.POSTGRES_PASSWORD }} \
            *.jar > app.log 2>&1 &
